# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	server_name mikurek.42.fr;

	ssl_certificate /etc/nginx/ssl/mikurek.crt;
    ssl_certificate_key /etc/nginx/ssl/mikurek.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 10m;

	root /var/www/html;

	index index.php index.html index.htm;

	location / {
			try_files $uri $uri/ /index.php$is_args$args;
		}

	location ~ \.php$ {
		try_files $uri =404;
		
		# FastCGI: przekierowanie żądania do kontenera PHP-FPM
		fastcgi_pass wordpress:9000;
		
		fastcgi_index index.php;
		include fastcgi_params;
		
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}


	# location / {
	# 	# First attempt to serve request as file, then
	# 	# as directory, then fall back to displaying a 404.
	# 	try_files $uri $uri/ =404;
	# }

	# # pass PHP scripts to FastCGI server
	# #
	# location ~ \.php$ {
	# 	include fastcgi_params;
	# 	fastcgi_pass wp-php:9000;
	# 	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	# }

}
