# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
	listen 80 default_server;
	listen [::]:80 default_server;

	server_name _;

	root /var/www/html;

	index index.php index.html index.htm;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# pass PHP scripts to FastCGI server
	#
	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass wp-php:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

}
