version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "80:80"
    volumes:
      - ${DATA_PATH}:/var/www/html
    restart: unless-stopped

  wordpress:
    container_name: wp-php
    build: ./requirements/wordpress
    volumes:
      - ${DATA_PATH}:/var/www/html
    restart: unless-stopped